#!/bin/bash
#PBS -N epic2
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=128:mem=256gb
#PBS -J 0-38

#change work directory to submission directory
cd $PBS_O_WORKDIR

#loading the Conda environment:
eval "$(~/miniforge3/bin/conda shell.bash hook)"

#activate conda environment
source activate hpcdemo


## SAMPLE SHEET ##
sheet="$HOME/chip_seq/mcd_et_al_2017/mcd_chip_sample_sheet_broad.csv"

## CONTROL INPUT FILES ##
capan_input="SRR11566129"
hpne_input="SRR11566178"
panc_input="SRR11566153"

## PATH TO BAMPE FILES ##
bam="$EPHEMERAL/chip_seq/ren_et_al_2021/bam_sorted_g"

## OUTPATH ##
output_path="$EPHEMERAL/chip_seq/ren_et_al_2021/epic2"
mkdir -p $output_path



## GENOME CHROM SIZES (hg38) ##
chrom_sizes="/rds/general/user/fno124/home/scripts/hg38.chrom.sizes"
egs=2913022398

# Extract the current sample from the sheet using PBS_ARRAY_INDEX
sample=$(sed -n "${PBS_ARRAY_INDEX}p" "$sheet")

# Parse the sample line into fields
IFS=',' read -r field1 field2 _ field4 _ field6_ <<< "$sample"



## Epic2 code ##

if [ "$field4" != "n/a" ]; then
        if [ "$field2" == "Capan-1" ]; then
                echo "$field1 is Capan-1"
                epic2 --treatment $field6 --control "$bam/$capan_input" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        elif [ "$field2" == "HPNE" ]; then
                echo "$field1 is HPNE"
                epic2 --treatment $field6 --control "$bam/$hpne_input" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        else
                echo "$field1 is PANC-1"
                epic2 --treatment $field6 --control "$bam/$panc_input" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        fi

fi
