#!/bin/bash
#PBS -N epic2
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=16:mem=64gb
#PBS -J 0-59

#change work directory to submission directory
cd $PBS_O_WORKDIR

#loading the Conda environment:
eval "$(~/miniforge3/bin/conda shell.bash hook)"

#activate conda environment
source activate hpcdemo


## SAMPLE SHEET ##
sheet="$HOME/chip_seq/mcd_et_al_2017/mcd_chip_sample_sheet_epic2.csv"

## CONTROL INPUT FILES ##
pri_input="a13_pri_input"
lg_input="a13_lg_input"
hpde_input="hpde_input"
a38_lg_input="a38_lg_70"
a38_per_input="a38_per_100"

## PATH TO BAMPE FILES ##
bam="$EPHEMERAL/chip_seq/mcd_et_al_2017/bam_sorted_g"

input="$EPHEMERAL/chip_seq/mcd_et_al_2017/combined_inputs"

## OUTPATH ##
output_path="$EPHEMERAL/chip_seq/mcd_et_al_2021/epic2"
mkdir -p $output_path


## GENOME CHROM SIZES (hg38) ##
chrom_sizes="/rds/general/user/fno124/home/scripts/hg38.chrom.sizes"
egs=2913022398

# Extract the current sample from the sheet using PBS_ARRAY_INDEX
sample=$(sed -n "${PBS_ARRAY_INDEX}p" "$sheet")

# Parse the sample line into fields
IFS=',' read -r field1 field2 _ field4 _ _ _ <<< "$sample"


## Epic2 code ##

if [ "$field4" != "n/a" ]; then
        if [ "$field2" == "primary tumor" ]; then
                echo "$field1 is primary tumor"
                epic2 --treatment "$bam/${field1}_filtered.bam" --control "$input/${pri_input}_filtered.bam" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        elif [ "$field2" == "lung metastasis" ]; then
                echo "$field1 is lung metastasis"
                epic2 --treatment "$bam/${field1}_filtered.bam" --control "$input/${a13_lg_input}_filtered.bam" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        elif [ "$field2" == "HPDE" ]; then
                echo "$field1 is HPDE"
                epic2 --treatment "$bam/${field1}_filtered.bam" --control "$input/${hpde_input}_filtered.bam" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        elif [ "$field2" == "100% (A38-Per)" ]; then
                echo "$field1 is A38 Peritoneum metastasis"
                epic2 --treatment "$bam/${field1}_filtered.bam" --control "$input/${a38_per_input}_filtered.bam" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        else
                echo "$field1 is A38 Lung metastasis"
                epic2 --treatment "$bam/${field1}_filtered.bam" --control "$input/${a38_lg_input}_filtered.bam" --guess-bampe --effective-genome-fraction $egs --chromsizes $chrom_sizes --output "$output_path/$field1.bed"
        fi

fi


## DEACTIVATE CONDA ##

conda deactivate
