#!/bin/bash
#PBS -N fastq_retreival
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=16:mem=64gb

#code to create a genome index using GENCODE GRCh

#change work directory to submission directory
cd $PBS_O_WORKDIR

#loading the Conda environment:
eval "$(~/miniforge3/bin/conda shell.bash hook)"

#activate conda environment
source activate hpcdemo

#code to create a genome index
STAR --runThreadN 8 --runMode genomeGenerate \
--genomeDir ~/GENCODE \
--genomeFastaFiles ~/GENCODE/GRCh38.primary_assembly.genome.fa \
--sjdbGTFfile ~/GENCODE/basic_gene_annotation_PRI.gtf \
--sjdbOverhang 149

conda deactivate
