#!/bin/bash
#PBS -N bwa-mem2_index
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=32:mem=128gb


#change work directory to submission directory
cd $PBS_O_WORKDIR

#load and activate conda work environment
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate hpcdemo



################################################# REFERENCE INDEX #####################################################################


#create bwa-mem2 ref index
bwa-mem2 index  -p "$HOME/BWA-MEM2-INDEX/reference_index" "$HOME/GENCODE_GENOME_INDEX_100bp/GRCh38.primary_assembly.genome.fa"

conda deactivate
