#!/bin/bash
#PBS -N macs2_peak_calling
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=128:mem=256gb


#change work directory to submission directory
cd $PBS_O_WORKDIR

#loading the Conda environment:
eval "$(~/miniforge3/bin/conda shell.bash hook)"

#activate conda environment
source activate hpcdemo

#load most recent version of python
module load python/3.5.4

#confirm python version
python --version

#sample sheet
sheet="$HOME/chip_seq/mcd_et_al_2017/mcd_chip_sample_sheet_MACS.csv"

#control input files:
a13_pri_input="$EPHEMERAL/chip_seq/mcd_et_al_2017/combined_inputs/a13_pri_input_filtered.bam"
a13_lg_input="$EPHEMERAL/chip_seq/mcd_et_al_2017/combined_inputs/a13_lg_input_filtered.bam"
hdpe_input="$EPHEMERAL/chip_seq/mcd_et_al_2017/combined_inputs/hpde_input_filtered.bam"
a38_lg_input="$EPHEMERAL/chip_seq/mcd_et_al_2017/combined_inputs/a38_lg_70.bam"
a38_per_input="$EPHEMERAL/chip_seq/mcd_et_al_2017/combined_inputs/a38_per_100.bam"

#path to bampe files
bam="$EPHEMERAL/chip_seq/mcd_et_al_2017/bam_sorted_g"

#outpath
output_path="$EPHEMERAL/chip_seq/mcd_et_al_2017/MACS2_results_1"
mkdir -p $output_path


###### MACS2 code ######

echo "A13 PRIMARY SAMPLES"

#if statements to retrieve the capan samples
while IFS=',' read -r field1 field2 field3 _ _; do
        if [ "$field3" != "n/a" ]; then
                if [ "$field2" == "primary tumor" ]; then
                        if [ "$field3" == "broad" ]; then
                                echo "${field1} is a BROAD peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a13_pri_input}" --to-large --keep-dup all --nolambda --broad -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        else
                                echo "${field1} is a NARROW peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a13_pri_input}" --to-large --keep-dup all --nolambda -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --trackline --bdg --outdir $output_path
                        fi
                fi
        fi
done < "$sheet"


echo "A13 LUNG SAMPLES"

#if statements to retrieve the hpne samples
while IFS=',' read -r field1 field2 field3 _ _; do #_ _ are placeholders for the other fields
        if [ "$field3" != "n/a" ]; then
                if [ "$field2" == "lung metastasis" ]; then
                        if [ "$field3" == "broad" ]; then
                                echo "${field1} is a BROAD peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a13_lg_input}" --to-large --keep-dup all --nolambda --broad -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        else
                                echo "${field1} is a NARROW peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a13_lg_input}" --to-large --keep-dup all --nolambda -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        fi
                fi
        fi
done < "$sheet"


echo "HDPE SAMPLES"

#if statements for HDPE
while IFS=',' read -r field1 field2 field3 _ _; do #_ _ are placeholders for the other fields
        if [ "$field3" != "n/a" ]; then
                if [ "$field2" == "HPDE" ]; then
                        if [ "$field3" == "broad" ]; then
                                echo "${field1} is a BROAD peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${hdpe_input}" --to-large --keep-dup all --nolambda --broad -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        else
                                echo "${field1} is a NARROW peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${hdpe_input}" --to-large --keep-dup all --nolambda -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        fi
                fi
        fi
done < "$sheet"


echo "A38 LUNG SAMPLES"
while IFS=',' read -r field1 field2 field3 _ _; do #_ _ are placeholders for the other fields
        if [ "$field3" != "n/a" ]; then
                if [ "$field2" == "70% (A38-Lg)" ]; then
                        if [ "$field3" == "broad" ]; then
                                echo "${field1} is a BROAD peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a38_lg_input}" --to-large --keep-dup all --nolambda --broad -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        else
                                echo "${field1} is a NARROW peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a38_lg_input}" --to-large --keep-dup all --nolambda -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                       fi
                fi
        fi
done < "$sheet"


echo "A38 PER SAMPLES"
while IFS=',' read -r field1 field2 field3 _ _; do #_ _ are placeholders for the other fields
        if [ "$field3" != "n/a" ]; then
                if [ "$field2" == "100% (A38-Per)" ]; then
                        if [ "$field3" == "broad" ]; then
                                "${field1} is a BROAD peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a38_per_input}" --to-large --keep-dup all --nolambda --broad -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        else
                                "${field1} is a NARROW peak"
                                macs2 callpeak -f BAMPE -t "$bam/${field1}_filtered.bam" -c "${a38_per_input}" --to-large --keep-dup all --nolambda -g 2913022398 --pvalue 0.05 --nomodel --name "${field1}" --bdg --trackline --outdir $output_path
                        fi
                fi
        fi
done < "$sheet"


echo "finish"
