#!/bin/bash
#PBS -N fastq_retreival
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=8:mem=64gb

#This code enables the retrieval of .sra files from ren_et_al.2021 RNA-seq dataset using the HPC

#change work directory to submission directory
cd $PBS_O_WORKDIR

#loading the Conda environment:
eval "$(~/miniforge3/bin/conda shell.bash hook)"

#activate hpcdemo environment
source activate hpcdemo


#csv file
csv=$HOME/rna_seq/seq_data/mcd_et_al_2017/SraRunTable_macdonald2017_rna.csv
srr=$( (tail -n +2 "$csv" | cut -d ',' -f 1) )

#make array
declare -a srr_array
srr_array=($srr)


#create a function to retrieve the fastq files
for item in "${srr_array[@]}"
do
        prefetch $item -O $EPHEMERAL/rna_seq/mcd_srr
done

#deactivate conda
conda deactivate
