#!/bin/bash
#PBS -N STAR_alignment
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=16:mem=64gb
#PBS -J 1-9

#change work directory to submission directory
cd $PBS_O_WORKDIR

#loading the Conda environment:
eval "$(~/miniforge3/bin/conda shell.bash hook)"
activate source hpcdemo

#SRR names via csv file
csv_path=$HOME/rna_seq/seq_data/ren_et_al_2021/ren_sra.csv
SRR=($(tail -n +2 "$csv_path" | cut -d ',' -f 1 ))

file_name_R1="${SRR[$PBS_ARRAY_INDEX]}_1.fastq"
file_name_R2="${SRR[$PBS_ARRAY_INDEX]}_2.fastq"

#set the paths for GTF file and outpath
inpath=$HOME/rna_seq/seq_data/ren_et_al_2021/cutadapt_out
outpath=$EPHEMERAL/rna_seq/Ren_BAM/
ano_gtf_path=$HOME/GENCODE/basic_gene_annotation_PRI.gtf

#STAR code
STAR --genomeDir ~GENCODE \
        --runThreadN 16 \
        --sjdbGTFfile $ano_gtf_path
        --readFilesIn $inpath/$file_name_R1 $inpath/$file_name_R2 \
        --quantMode GeneCounts \
        --twopassMode Basic \
        --outWigType bedGraph \
        --outWigStrand Stranded \
        --outFileNamePrefix ${outpath}/"${SRR[$PBS_ARRAY_INDEX]"}  \
        --outSAMtype BAM SortedByCoordinate \
        --outSAMunmapped Within \
        --outSAMattributes Standard


conda deactivate
