#!/bin/bash
#PBS -N fanc_ab_ev
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=4:mem=8gb
#PBS -J 0-9

#change work directory to submission directory
cd $PBS_O_WORKDIR

#loading the Conda environment:
eval "$(~/miniforge3/bin/conda shell.bash hook)"

#activate conda environment
source activate fanc_env


#samples array
samples=(SRR11566146 SRR11566147 SRR11566148 SRR11566149 SRR11566165 SRR11566171 SRR11566172 SRR11566176 SRR11566187 SRR11566188)

#resolution
res=1000000

#genome FASTA
genome_fa="$HOME/GENCODE_GENOME_INDEX_100bp/GRCh38.primary_assembly.genome.fa"

#in- and outpath
path="$EPHEMERAL/hi-c/ren_et_al_2021/fanc/ab/${res}/${samples[$PBS_ARRAY_INDEX]}"
#path="$EPHEMERAL/hi-c/ren_et_al_2021/fanc/fanc_hic/${samples[$PBS_ARRAY_INDEX]}"
outpath="$EPHEMERAL/hi-c/ren_et_al_2021/fanc/ab_1/${res}/${samples[$PBS_ARRAY_INDEX]}"
mkdir -p "$outpath"


#name of file
name="${samples[$PBS_ARRAY_INDEX]}_${res}_fanc"

# A/B compartments
#fanc compartments -v "$path/${hic_suffix}" "${path}/${ab_suffix}"


# A/B compartments
fanc compartments -g "$genome_fa" \
	-i 2 -v "${outpath}/${name}_i2.ev.txt" \
	"${path}/${name}.ab"

#deactivate conda env
conda deactivate
